### ISSUE TITLE
Block order issue

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Sharing#22]
The module breaks the site if the first block has no attached items. 

`Notice: Undefined offset: 0 in /websites/omekadev/home/www/omeka-s/modules/Sharing/Module.php on line 137 Fatal error: Call to a member function item() on a non-object in /websites/omekadev/home/www/omeka-s/modules/Sharing/Module.php on line 138`

**Comment by patrickmj** [comment]
Fixed in https://github.com/omeka-s-modules/Sharing/commit/5049631288776297cffaeb0a38bf8513b9e56acb
