### ISSUE TITLE
Decide which sites/services we want to share to

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Sharing#3]
Consensus was that we should produce our own links to a select number of services/sites. So, which ones?
- Twitter
- Facebook
- Pinterest
- Email
- ~~LinkedIn~~
- ~~Google +~~
- Tumblr

Any thoughts or others to add? @sleon, @jimsafley, @zerocrates, @sheilabrennan, @mebrett, @kalbers

**Comment by mebrett** [comment]
Definitely: twitter, facebook, email
I'd vote for tumblr as well.

**Comment by sheilabrennan** [comment]
How about Instagram

**Comment by sheilabrennan** [comment]
I'd remove LinkedIn, Google+

**Comment by mebrett** [comment]
Can you share to instagram?

**Comment by patrickmj** [comment]
@sheilabrennan @mebrett Since AddThis doesn't have an option for Instagram, and some googling turned up negative answers, looks like no Instagram

**Comment by sheilabrennan** [comment]
Alrighty, guess it is only follow buttons that they allow.

**Comment by patrickmj** [comment]
Final call. Is this list good for what we want to share to?

 @sleon, @jimsafley, @zerocrates, @sheilabrennan, @mebrett, @kalbers, @kimisgold (Kim, sorry, didn't mean to leave you off original comment)

**Comment by kimisgold** [comment]
Looks fine.

**Comment by sharonmleon** [comment]
Looks good to me.

**Comment by mebrett** [comment]
Thirded.

**Comment by zerocrates** [comment]
The 5 non-crossed out options in the summary? Looks fine.
