### ISSUE TITLE
Testing new event options

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Sharing#31]
Sharing now has an option under site settings to choose whether to show the sharing buttons at the top or the bottoms of the pages where it works. This should be looked at across all the themes to see if they show up okay with both options (and that the sharing still works to the various sites, though a doubt there's been changes there).

Sharing -- latest master branch
Themes -- I think all of those are for latest master
S Core -- latest develop

**Comment by mebrett** [comment]
Are there any specific expected behaviors or anticipated bugs you want us to look for?

**Comment by patrickmj** [comment]
Not really...basically just whether the buttons show up reasonably in the themes, wherever they are placed (the top option and event is new). And whether anything broke.

**Comment by mebrett** [comment]
And just to double-check: sharing buttons should show up on all pages, not just item-show ones

**Comment by patrickmj** [comment]
Right now, it should be pages, item-show, and browse pages. If they make sense to have elsewhere but aren't there, those make sense as new issues.

**Comment by jannellelegg** [comment]
Testing with the default theme, top and bottom:

Top:
- they are appearing at the top of each page and sharing works.
- some alignment issues on pages - gap at the top/left perhaps because of the search bar?
  ![default-top](https://cloud.githubusercontent.com/assets/5897725/20272682/af9bf7dc-aa5c-11e6-872c-ab6fd842b1a3.png)
- Alignment works better on subpages- still a gap on the left.
  ![default-top2](https://cloud.githubusercontent.com/assets/5897725/20272765/ef5aa2ba-aa5c-11e6-976c-b345f25457fa.png)
- Icons are also awkwardly spaced on item pages:
  ![default-top3](https://cloud.githubusercontent.com/assets/5897725/20272924/79122604-aa5d-11e6-9872-c45146d3398e.png)

Bottom: 
- they are appearing at the bottom of each page and sharing works.
- alignment is also slightly indented from the left:

page/subpage:
![default-bottom](https://cloud.githubusercontent.com/assets/5897725/20273051/e40f37bc-aa5d-11e6-85dc-fd9ef5b46a27.png)

item page:
![default-bottom2](https://cloud.githubusercontent.com/assets/5897725/20273143/295ee5c4-aa5e-11e6-902e-4278cf5dc2e0.png)

**Comment by patrickmj** [comment]
Pushed up a CSS change to master branch that should resolve the spacing issues. It's worth looking at across browsers to make sure that there isn't a browser quirk.

**Comment by patrickmj** [comment]
Pinging @mebrett @jannellelegg @alyssafahringer on whether the fixes on master resolve the above issues.

**Comment by jannellelegg** [comment]
Testing with default theme, top and bottom.

Top: buttons worked across all browsers and buttons populated across all browsers

Left alignment issue seems to be specific to Chrome:
![2 default top chrome](https://cloud.githubusercontent.com/assets/5897725/20488336/9dc37f80-afd4-11e6-942a-790b4d5efb54.png)

Safari:
![2 default top safari](https://cloud.githubusercontent.com/assets/5897725/20488350/a7c469ea-afd4-11e6-9dc1-ffaf0defdaed.png)

Firefox:
![2 default top firefox](https://cloud.githubusercontent.com/assets/5897725/20488355/ae9164da-afd4-11e6-8d37-c861d5a04850.png)


Bottom:  buttons worked across all browsers and buttons populated across all browsers

Left alignment issue, again, seems to be specific to Chrome:
![2 default bottom chrome](https://cloud.githubusercontent.com/assets/5897725/20489418/91846f28-afd8-11e6-9349-454010555a4e.png)

Safari:
![2 default bottom safari](https://cloud.githubusercontent.com/assets/5897725/20489410/8cee5596-afd8-11e6-899b-235aef75977e.png)

Firefox:
![2 default bottom firefox](https://cloud.githubusercontent.com/assets/5897725/20489421/96aa0152-afd8-11e6-885c-2f07613f4aac.png)

**Comment by jannellelegg** [comment]
Other themes: 

CenterRow:
- issue with alignment exists on Chrome (top/bottom)

![centerrow top chrome](https://cloud.githubusercontent.com/assets/5897725/20489934/5110ecc6-afda-11e6-9915-c3bd8539998b.png)
![centerrow bottom chrome](https://cloud.githubusercontent.com/assets/5897725/20489940/557dff24-afda-11e6-9a2f-a0b009315eab.png)

- Item page is not populating the share buttons (in Chrome, Safari, Firefox) when it is set to top. 

- alignment is a bit awkward on the item pages when set to bottom. It's not aligning with the text or centering as the other items do on the page.

Chrome:
![centerrow bottom chrome item](https://cloud.githubusercontent.com/assets/5897725/20490132/e2a1e4ec-afda-11e6-9f2d-dfd24a221e1d.png)
Firefox:
![centerrow bottom firefox item](https://cloud.githubusercontent.com/assets/5897725/20490147/ee447c88-afda-11e6-9b26-5b67939de336.png)
Safari: 
![centerrow bottom safari item](https://cloud.githubusercontent.com/assets/5897725/20490167/faa231aa-afda-11e6-8674-c44bce03f3bb.png)

**Comment by jannellelegg** [comment]
The Daily:

- issue with alignment exists on Chrome (top/bottom):
![the daily top chrome](https://cloud.githubusercontent.com/assets/5897725/20493928/bad708e4-afe8-11e6-942a-dee6d7100061.png)
![the daily bottom chrome](https://cloud.githubusercontent.com/assets/5897725/20493943/c52438e4-afe8-11e6-9828-06e010084f32.png)

Bottom item page:
![the daily bottom chrome item](https://cloud.githubusercontent.com/assets/5897725/20493947/c90251bc-afe8-11e6-8782-138274b7e570.png)

In firefox and safari, buttons are populating appropriately - no alignment issues.

**Comment by jannellelegg** [comment]
Cozy:

- similar to the other themes, in Chrome there is an indention from the left on when set to top or bottom:
![cozy top chrome](https://cloud.githubusercontent.com/assets/5897725/20494149/ab692a62-afe9-11e6-9c17-9486b6e304dc.png)
![cozy bottom chrome](https://cloud.githubusercontent.com/assets/5897725/20494351/7e8dcb1e-afea-11e6-93f2-849e7f510cac.png)


- On the item page, in Chrome (not in Safari or Firefox), the buttons overlap with text on the page:
![cozy top chrome item](https://cloud.githubusercontent.com/assets/5897725/20494143/a7ea1356-afe9-11e6-826a-157878e42e04.png)

**Comment by zerocrates** [comment]
Is there a link to this site?

I can't seem to reproduce the left alignment issue.

**Comment by mebrett** [comment]
http://dev.omeka.org/mebrett/testomekas/s/FlicksOfThe80s/page/home

**Comment by kimisgold** [comment]
Even looking at that link, I don't see the left alignment from the screenshots using Cozy on Chrome.

**Comment by mebrett** [comment]
I'm not seeing the alignment issues in Chrome, but will second the issue on Center Row where sharing buttons are not showing up on item pages.

ex http://dev.omeka.org/mebrett/testomekas/s/austen/item/3493

**Comment by mebrett** [comment]
Alignment issue that Jannelle experienced was probably caused by an adblocking plugin for Chrome. Ad Blockers tend to interfere with (at least make wonky) Sharing.

**Comment by jannellelegg** [comment]
Thanks @mebrett for troubleshooting with me- disabling my adblocker/plugins seems to have resolved the left-alignment issue for Chrome for each of the themes.

Outstanding issues are:
- Centerow (top) - buttons do not appear 
- Centerrow (bottom) - buttons are slightly out of alignment with the "Powered by Omeka S" text

**Comment by jannellelegg** [comment]
Update:
The Center Row (top) issue has been resolved.
The Center Row (bottom) still slightly unaligned but not a functional problem. [See example](http://dev.omeka.org/mebrett/testomekas/s/FlicksOfThe80s/page/home)

**Comment by kimisgold** [comment]
@jannellelegg Could you publish the site from the example? It's currently not viewable to those without a login to Megan's installation.

**Comment by mebrett** [comment]
I just made it public

**Comment by mebrett** [comment]
It looks to me as though both of the final issues in Jannelle's comments have been resolved.

**Comment by zerocrates** [comment]
Then I deem it closed
