### ISSUE TITLE
Inconsistent bottom alignment on pages

### ISSUE THREAD

**Issue by mebrett** [omeka-s-modules/Sharing#32]
On pages with prev/next buttons, the sharing buttons appear above prev/next in Center Row and Default, and below in The Daily. They're mostly above in Cozy, except in this one instance where the last block is an Item with Metadata - they're tucked up under the file. 
![screen shot 2016-11-11 at 2 50 30 pm](https://cloud.githubusercontent.com/assets/2314070/20228402/fd22b652-a81e-11e6-8334-5f8710ab9ad0.png)

**Comment by patrickmj** [comment]
We're generally going with adding content from modules inside the pagination buttons. I think that's been made consistent, but if there are still inconsistencies it's worth an issue.

What's in this screenshot is a bigger question of how the styling works -- it might be as simple as a `clear` setting on what Sharing does, but guidance from @kimisgold is in order.

**Comment by patrickmj** [comment]
From what I'm looking at on develop of Omeka S, master of Cozy, and this morning's master of Sharing, it looks okay on my laptop, but confirmation is definitely in order.

**Comment by mebrett** [comment]
What does it look like on this page? Because I still have the weird alignment on Chrome, Firefox, and Safari http://dev.omeka.org/mebrett/testomekas/s/austen/page/published

**Comment by patrickmj** [comment]
Thanks, with that I could reproduce it. Latest master should have a fix, though it seems like it could pop up again with different page setups

**Comment by mebrett** [comment]
That did indeed fix it.
