### ISSUE TITLE
Direct user to settings on activation

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Sharing#33]
Upon installing and activating the module, it wasn't obvious to me where to find the settings for Sharing, or even if it was actually working since none of the options are selected by default.

**Comment by patrickmj** [comment]
Not sure that's feasible, since all of Sharing's settings are per site.

**Comment by patrickmj** [comment]
Some kind of message giving guidance is probably in order, as well as having things in the documentation
