### ISSUE TITLE
Meta elements

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Sharing#40]
When the module is active, it outputs the following OG tags on an item page:

```
<meta property="og&#x3A;description" content="A&#x20;book">
<meta property="og&#x3A;image" content="http&#x3A;&#x2F;&#x2F;dev.omeka.org&#x2F;amayer&#x2F;amayer-s&#x2F;omeka-s&#x2F;files&#x2F;large&#x2F;e7f2bb833402044b178b03225b37683c4449ce6f.jpg">
<meta property="og&#x3A;title" content="A&#x20;Tale&#x20;of&#x20;Three&#x20;Bonnets&#x20;in&#x20;Four&#x20;Cantos&#x20;&#xB7;&#x20;My&#x20;Omeka&#x20;S&#x20;Installation">
<meta property="og&#x3A;type" content="website">
<meta property="og&#x3A;url" content="http&#x3A;&#x2F;&#x2F;dev.omeka.org&#x2F;amayer&#x2F;amayer-s&#x2F;omeka-s&#x2F;s&#x2F;my-second-omeka-s-site&#x2F;item&#x2F;3618">
<meta property="og&#x3A;description" content="A&#x20;book">
<meta property="og&#x3A;image" content="http&#x3A;&#x2F;&#x2F;dev.omeka.org&#x2F;amayer&#x2F;amayer-s&#x2F;omeka-s&#x2F;files&#x2F;large&#x2F;e7f2bb833402044b178b03225b37683c4449ce6f.jpg">
```

There is a duplication problem: I don't know why it's sending og:image and og:description twice. The values are identical. 

It's also not sending the exact page title in the og:title - should include the name of the site, right? "Site Title - Item Title - Installation Title" is what's being sent to the `<title>`.

[dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-omeka-s-site/item/3618](dev.omeka.org/amayer/amayer-s/omeka-s/s/my-second-omeka-s-site/item/3618)

**Comment by jimsafley** [comment]
og duplication should be fixed in the recent barrage of commits.
