### ISSUE TITLE
Documentation: oEmbed feature

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Sharing#42]
The only notable change in the next release is the addition of [oEmbed](https://oembed.com/). Like Open Graph, it makes itself discoverable on public item pages, media pages, and site pages; but instead of `<meta>` tags it uses a `<link type="application/json+oembed">` tag that points to the newly added oEmbed endpoint. This new ability to be discoverable will need to be documented.

**Comment by allanaaa** [comment]
What is it I'm looking for exactly? I see this in the head:
`<link href="http://dev.omeka.org/amayer/amayer-s/omeka-s/oembed?url=http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/testing-layouts" rel="alternate" type="application/json+oembed" title="Testing Layouts">`

So the endpoint is `http://dev.omeka.org/amayer/amayer-s/omeka-s/oembed`. But this validator doesn't seem to like the input:
https://embed.ly/providers/validate/oembed?endpoint=http%3A%2F%2Fdev.omeka.org%2Famayer%2Famayer-s%2Fomeka-s%2Foembed&url=http%3A%2F%2Fdev.omeka.org%2Famayer%2Famayer-s%2Fomeka-s%2Fs%2Fmy-omeka-s-site%2Fpage%2Ftesting-layouts

**Comment by jimsafley** [comment]
Yes, it's that `application/json+oembed` link that services will see. I just pushed a fix that may make that validator work. There's also the [Iframely URL Debugger](https://debug.iframely.com/), if you prefer.

**Comment by allanaaa** [comment]
Yep, that fixes a few of the validators I tried. Thanks!
