### ISSUE TITLE
Deprecated  `Passing null to strstr()`

### ISSUE THREAD

**Issue by cy-altern** [omeka-s-modules/Sharing#43]
On a page with a **oEmbed** video got error :
```
Deprecated: strstr(): Passing null to parameter #1 ($haystack) of type string is deprecated in .../modules/Sharing/Module.php on line 264
```
Note that in the database's `media` table, the `media_type` field is empty (which is "normal" since the oEmbed call can provide many possible types...)

Versions :
Module Sharing up to date (rev. 90057c12605405efba516337ff6ef4d3d5231335) + Omeka S 4.0.1 (rev. 47888f351dd574dfcb885e317a546ad738c13295)

**Comment by zerocrates** [comment]
Yeah, this is a PHP 8.1 deprecation that only happens here when dealing with media that don't have a media type. As you say that's normal for oEmbed, and really any media that doesn't correspond to a stored file.

If you pull in the latest commit it should resolve this notice for you.

**Comment by cy-altern** [comment]
thanks for your quick response !
