### ISSUE TITLE
Twitter JS gets loaded even when disabled

### ISSUE THREAD

**Issue by ManOnDaMoon** [omeka-s-modules/Sharing#45]
https://github.com/omeka-s-modules/Sharing/blob/e66abd3c8f618129f101a66576e47227df385436/Module.php#L192

Hello!

I was wondering if there is any particular reason to load the twitter JS script even when it is not enabled in a site's settings?
Other services' scripts are then loaded only when necessary in the loop that follows:
https://github.com/omeka-s-modules/Sharing/blob/e66abd3c8f618129f101a66576e47227df385436/Module.php#L231

**Comment by Daniel-KM** [comment]
This is fixed in #44 .
