### ISSUE TITLE
Testing: New features

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Sharing#46]
A few new features need testing:

- "Single button" setting in site settings under "Sharing". This setting consolidates sharing buttons under one share icon.
- "Sharing" page block layout. This layout displays sharing buttons on site pages.
- "Sharing" resource block layout for item page and media page This layout displays sharing buttons on resource pages.

**Comment by allanaaa** [comment]
Using a page block and also having the site set to "top" or "bottom" means the button shows up twice:

<img width="579" alt="Screenshot 2024-06-19 at 15 12 39" src="https://github.com/omeka-s-modules/Sharing/assets/28012148/6ff115e4-c1a5-4e4e-acb8-dc360b3a3887">

Do you want to amend that to be more like the TOC block, where the default page display disappears when you use a page block?

**Comment by allanaaa** [comment]
I forget: is this supposed to appear on Faceted Browse pages, the Map Browse page, etc? It isn't at the moment. But I can note that in the docs if it's not intended.

**Comment by allanaaa** [comment]
The font-awesome icon for "Embed codes" isn't showing: 

<img width="298" alt="Screenshot 2024-06-19 at 15 42 56" src="https://github.com/omeka-s-modules/Sharing/assets/28012148/f2196c35-0a51-4ce7-a889-764080a497e6">

Same problem as usual - the font-weight needs to be set to "bold" or a higher number.

<img width="680" alt="Screenshot 2024-06-19 at 15 44 19" src="https://github.com/omeka-s-modules/Sharing/assets/28012148/29c36e41-ada3-4f34-a91c-924b4c4bb63f">

**Comment by allanaaa** [comment]
The behaviour is also not ideal for the page blocks when in a narrow space. Note the text overflows its own button. @kimisgold would you jump in on the CSS for this one?

<img width="430" alt="Screenshot 2024-06-19 at 15 57 52" src="https://github.com/omeka-s-modules/Sharing/assets/28012148/b5f415fb-b962-4d35-ba84-3ba8fa05bbe4">

**Comment by jimsafley** [comment]
> Using a page block and also having the site set to "top" or "bottom" means the button shows up twice. Do you want to amend that to be more like the TOC block, where the default page display disappears when you use a page block?

I don't think this will be a problem. A site administrator would set "Sharon buttons placement" to "Using blocks" if they intend to add the buttons using blocks. If it does become a problem, we'll just advise them to change to "Using blocks."

> I forget: is this supposed to appear on Faceted Browse pages, the Map Browse page, etc? It isn't at the moment. But I can note that in the docs if it's not intended.

Sharing buttons only appear on public site pages, and public item and media resource pages.

> The font-awesome icon for "Embed codes" isn't showing:

@kimisgold Do you know what's happening [here](https://github.com/omeka-s-modules/Sharing/issues/46#issuecomment-2179372547)?

**Comment by jimsafley** [comment]
The outstanding style issues should not delay release. I'll make a separate issue pointing to this issue.
